---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clickhouse-keeper.altinity.com
  resources:
  - clickhousekeeperinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clickhouse-keeper.altinity.com
  resources:
  - clickhousekeeperinstallations/finalizers
  verbs:
  - update
- apiGroups:
  - clickhouse-keeper.altinity.com
  resources:
  - clickhousekeeperinstallations/status
  verbs:
  - get
- apiGroups:
  - clickhouse.altinity.com
  resources:
  - clickhouseinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clickhouse.altinity.com
  resources:
  - clickhouseinstallations/finalizers
  verbs:
  - update
- apiGroups:
  - clickhouse.altinity.com
  resources:
  - clickhouseinstallations/status
  verbs:
  - get
